const express = require("express");

const app = express();
const https=require('https')

var options = {
  dotfiles: 'ignore',
  etag: false,
  extensions: ['htm', 'html'],
  index: false,
  maxAge: '1d',
  redirect: false,
  setHeaders: function (res, path, stat) {
    res.set('x-timestamp', Date.now())
  }
}


//in options.rBody is the result , options.hostname , options.path
function client(options,onResp){
	const pds = options&&options.postData?querystring.stringify(options.postData):0

	if(!options)options = {};
	if(!options.hostname)options.hostname='192.168.1.122'
	if(!options.port)options.port=80
	if(!options.path)options.path='/'
	if(!options.method)options.method= 'GET'
	options.chunks=[];var msgs=[]

	if(pds){
		options.method='POST';
		var h=options. headers
		if(!h)
			h=options. headers={}
		if(!h['Content-Type'])
			h['Content-Type']='application/x-www-form-urlencoded';
		if(!h['Content-Length'])
			h['Content-Length']=Buffer.byteLength(pds);
	}
	console.log('srvr.http:options=',options);
	const req = https.request(options, (res) => {
		  var msg=`STATUS: ${res.statusCode} 
			, HEADERS: ${JSON.stringify(res.headers)}`
		msgs.push(msg)
		console.log('srvr.http:clb-resp:options=',options,',msg=',msg,',resp=',res);
		res.setEncoding('utf8');
		res.on('data', (chunk) => {
			console.log('srvr.http:clb-resp:evt-data:options=',options,',resp=',res,',chunk=',chunk);//console.log(`BODY: ${chunk}`);
			options.chunks.push(chunk)
		  });
		  res.on('end', () => {
			msgs.push('http.request:completed-chunks')//console.log('No more data in response.');
			options.rBody=options.chunks.join('')
			console.log('srvr.http:clb-resp:evt-end:options=',options,',resp=',res,'respBody=',options.rBody);
			if(onResp)
				onResp(res,options)
		  });
		}//onResp
	);//http.request

	req.on('error', (e) => {
		const msg=`problem with request: ${e.message}`
		msgs.push(msg);
		console.log('srvr.http:clb-error:options='
			,options,',msg=',msg,',error=',e);
		
		if(onResp)
			onResp(e,options)
	});

	if(pds)
		// Write data to request body
		req.write(pds);
	req.end();
}//function

app.use(express.static('./', options))

app.get('/weather/:p', function (req, res) {
/*	client({hostname:'api.darksky.net',port:443,protocol:'https:'
		,path:'forecast/6fdf31d75af984e318187f1f78d17a7d/'
			+req.params.p}
		,q=> res.json(q.data) 
	)*/
	
	res.json({
    "latitude": 34.1139,
    "longitude": -118.4068,
    "timezone": "America/Los_Angeles",
    "currently": {
        "time": 1575687424,
        "summary": "Light Rain",
        "icon": "rain",
        "nearestStormDistance": 0,
        "precipIntensity": 0.017,
        "precipIntensityError": 0.002,
        "precipProbability": 1,
        "precipType": "rain",
        "temperature": 56.12,
        "apparentTemperature": 56.12,
        "dewPoint": 54.52,
        "humidity": 0.94,
        "pressure": 1021.2,
        "windSpeed": 3.14,
        "windGust": 5.45,
        "windBearing": 203,
        "cloudCover": 0.75,
        "uvIndex": 0,
        "visibility": 10,
        "ozone": 285.1
    },
    "minutely": {
        "summary": "Light rain stopping in 7 min.",
        "icon": "rain",
        "data": [{
                "time": 1575687420,
                "precipIntensity": 0.017,
                "precipIntensityError": 0.002,
                "precipProbability": 1,
                "precipType": "rain"
            }, {
                "time": 1575687480,
                "precipIntensity": 0.018,
                "precipIntensityError": 0.002,
                "precipProbability": 1,
                "precipType": "rain"
            }, {
                "time": 1575687540,
                "precipIntensity": 0.015,
                "precipIntensityError": 0.003,
                "precipProbability": 1,
                "precipType": "rain"
            }, {
                "time": 1575687600,
                "precipIntensity": 0.011,
                "precipIntensityError": 0.004,
                "precipProbability": 1,
                "precipType": "rain"
            }, {
                "time": 1575687660,
                "precipIntensity": 0.008,
                "precipIntensityError": 0.003,
                "precipProbability": 0.97,
                "precipType": "rain"
            }, {
                "time": 1575687720,
                "precipIntensity": 0.006,
                "precipIntensityError": 0.003,
                "precipProbability": 0.82,
                "precipType": "rain"
            }, {
                "time": 1575687780,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.002,
                "precipProbability": 0.54,
                "precipType": "rain"
            }, {
                "time": 1575687840,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.002,
                "precipProbability": 0.32,
                "precipType": "rain"
            }, {
                "time": 1575687900,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.002,
                "precipProbability": 0.18,
                "precipType": "rain"
            }, {
                "time": 1575687960,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.09,
                "precipType": "rain"
            }, {
                "time": 1575688020,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.04,
                "precipType": "rain"
            }, {
                "time": 1575688080,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.02,
                "precipType": "rain"
            }, {
                "time": 1575688140,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.01,
                "precipType": "rain"
            }, {
                "time": 1575688200,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688260,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688320,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688380,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688440,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688500,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688560,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688620,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688680,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688740,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688800,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688860,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688920,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575688980,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689040,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689100,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689160,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689220,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689280,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689340,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689400,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689460,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689520,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689580,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689640,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689700,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689760,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689820,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689880,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575689940,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690000,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690060,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690120,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690180,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690240,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690300,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690360,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690420,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690480,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690540,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690600,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690660,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690720,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690780,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690840,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690900,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575690960,
                "precipIntensity": 0,
                "precipProbability": 0
            }, {
                "time": 1575691020,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Possible light rain starting tomorrow morning.",
        "icon": "rain",
        "data": [{
                "time": 1575684000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.8,
                "apparentTemperature": 56.8,
                "dewPoint": 54.17,
                "humidity": 0.91,
                "pressure": 1020.8,
                "windSpeed": 3.4,
                "windGust": 5.24,
                "windBearing": 196,
                "cloudCover": 0.78,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.7
            }, {
                "time": 1575687600,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0019,
                "precipProbability": 1,
                "precipType": "rain",
                "temperature": 56.09,
                "apparentTemperature": 56.09,
                "dewPoint": 54.53,
                "humidity": 0.94,
                "pressure": 1021.2,
                "windSpeed": 3.13,
                "windGust": 5.47,
                "windBearing": 203,
                "cloudCover": 0.75,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.1
            }, {
                "time": 1575691200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.001,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 55.67,
                "apparentTemperature": 55.67,
                "dewPoint": 54.38,
                "humidity": 0.95,
                "pressure": 1021.3,
                "windSpeed": 3.01,
                "windGust": 5.79,
                "windBearing": 169,
                "cloudCover": 0.77,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.8
            }, {
                "time": 1575694800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.001,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperature": 55.66,
                "apparentTemperature": 55.66,
                "dewPoint": 53.13,
                "humidity": 0.91,
                "pressure": 1021.5,
                "windSpeed": 3.1,
                "windGust": 6.47,
                "windBearing": 95,
                "cloudCover": 0.74,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.7
            }, {
                "time": 1575698400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0034,
                "precipProbability": 0.09,
                "precipType": "rain",
                "temperature": 55.76,
                "apparentTemperature": 55.76,
                "dewPoint": 52.38,
                "humidity": 0.88,
                "pressure": 1021.5,
                "windSpeed": 3.94,
                "windGust": 8.17,
                "windBearing": 103,
                "cloudCover": 0.67,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 287.2
            }, {
                "time": 1575702000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0052,
                "precipProbability": 0.15,
                "precipType": "rain",
                "temperature": 55.51,
                "apparentTemperature": 55.51,
                "dewPoint": 51.79,
                "humidity": 0.87,
                "pressure": 1021.4,
                "windSpeed": 4.13,
                "windGust": 7.79,
                "windBearing": 97,
                "cloudCover": 0.66,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.8
            }, {
                "time": 1575705600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0078,
                "precipProbability": 0.2,
                "precipType": "rain",
                "temperature": 55.51,
                "apparentTemperature": 55.51,
                "dewPoint": 51.26,
                "humidity": 0.86,
                "pressure": 1021.2,
                "windSpeed": 3.91,
                "windGust": 6.41,
                "windBearing": 69,
                "cloudCover": 0.66,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.9
            }, {
                "time": 1575709200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0101,
                "precipProbability": 0.21,
                "precipType": "rain",
                "temperature": 55.44,
                "apparentTemperature": 55.44,
                "dewPoint": 50.96,
                "humidity": 0.85,
                "pressure": 1020.8,
                "windSpeed": 3.94,
                "windGust": 5.85,
                "windBearing": 70,
                "cloudCover": 0.63,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.4
            }, {
                "time": 1575712800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.01,
                "precipProbability": 0.23,
                "precipType": "rain",
                "temperature": 55.28,
                "apparentTemperature": 55.28,
                "dewPoint": 50.77,
                "humidity": 0.85,
                "pressure": 1020.7,
                "windSpeed": 4.26,
                "windGust": 6.31,
                "windBearing": 83,
                "cloudCover": 0.72,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.8
            }, {
                "time": 1575716400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0069,
                "precipProbability": 0.2,
                "precipType": "rain",
                "temperature": 55.32,
                "apparentTemperature": 55.32,
                "dewPoint": 50.74,
                "humidity": 0.85,
                "pressure": 1021,
                "windSpeed": 4.45,
                "windGust": 6.54,
                "windBearing": 74,
                "cloudCover": 0.94,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.6
            }, {
                "time": 1575720000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0136,
                "precipProbability": 0.26,
                "precipType": "rain",
                "temperature": 55.34,
                "apparentTemperature": 55.34,
                "dewPoint": 50.98,
                "humidity": 0.85,
                "pressure": 1021.2,
                "windSpeed": 4.55,
                "windGust": 6.7,
                "windBearing": 48,
                "cloudCover": 0.97,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 287.3
            }, {
                "time": 1575723600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.026,
                "precipProbability": 0.35,
                "precipType": "rain",
                "temperature": 54.86,
                "apparentTemperature": 54.86,
                "dewPoint": 51.88,
                "humidity": 0.9,
                "pressure": 1021.2,
                "windSpeed": 4.28,
                "windGust": 6.39,
                "windBearing": 60,
                "cloudCover": 0.98,
                "uvIndex": 0,
                "visibility": 9.45,
                "ozone": 287.9
            }, {
                "time": 1575727200,
                "summary": "Possible Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0268,
                "precipProbability": 0.4,
                "precipType": "rain",
                "temperature": 54.82,
                "apparentTemperature": 54.82,
                "dewPoint": 52.64,
                "humidity": 0.92,
                "pressure": 1021,
                "windSpeed": 4.44,
                "windGust": 6.7,
                "windBearing": 66,
                "cloudCover": 0.99,
                "uvIndex": 0,
                "visibility": 9.784,
                "ozone": 288.4
            }, {
                "time": 1575730800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0083,
                "precipProbability": 0.22,
                "precipType": "rain",
                "temperature": 55.05,
                "apparentTemperature": 55.05,
                "dewPoint": 53.47,
                "humidity": 0.94,
                "pressure": 1021.1,
                "windSpeed": 4.62,
                "windGust": 7.38,
                "windBearing": 80,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 288.8
            }, {
                "time": 1575734400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0058,
                "precipProbability": 0.17,
                "precipType": "rain",
                "temperature": 56.13,
                "apparentTemperature": 56.13,
                "dewPoint": 54.48,
                "humidity": 0.94,
                "pressure": 1021.4,
                "windSpeed": 4.7,
                "windGust": 8.08,
                "windBearing": 91,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 289
            }, {
                "time": 1575738000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0057,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 58.81,
                "apparentTemperature": 58.81,
                "dewPoint": 54.32,
                "humidity": 0.85,
                "pressure": 1022.1,
                "windSpeed": 4.02,
                "windGust": 5.83,
                "windBearing": 112,
                "cloudCover": 1,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 289
            }, {
                "time": 1575741600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0061,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 59.49,
                "apparentTemperature": 59.49,
                "dewPoint": 54.97,
                "humidity": 0.85,
                "pressure": 1022.4,
                "windSpeed": 4.09,
                "windGust": 6.32,
                "windBearing": 127,
                "cloudCover": 1,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 289.1
            }, {
                "time": 1575745200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0059,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 60.45,
                "apparentTemperature": 60.45,
                "dewPoint": 55.49,
                "humidity": 0.84,
                "pressure": 1021.8,
                "windSpeed": 4.2,
                "windGust": 6.38,
                "windBearing": 137,
                "cloudCover": 1,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 289.4
            }, {
                "time": 1575748800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0056,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 60.89,
                "apparentTemperature": 60.89,
                "dewPoint": 56.15,
                "humidity": 0.84,
                "pressure": 1020.8,
                "windSpeed": 4.34,
                "windGust": 6.31,
                "windBearing": 146,
                "cloudCover": 0.99,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 289.8
            }, {
                "time": 1575752400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0057,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 60.8,
                "apparentTemperature": 60.8,
                "dewPoint": 56.69,
                "humidity": 0.86,
                "pressure": 1020.2,
                "windSpeed": 4.44,
                "windGust": 6.37,
                "windBearing": 152,
                "cloudCover": 0.99,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 290.4
            }, {
                "time": 1575756000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0068,
                "precipProbability": 0.16,
                "precipType": "rain",
                "temperature": 61.35,
                "apparentTemperature": 61.35,
                "dewPoint": 57.22,
                "humidity": 0.86,
                "pressure": 1019.8,
                "windSpeed": 4.43,
                "windGust": 6.69,
                "windBearing": 157,
                "cloudCover": 0.99,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 291.2
            }, {
                "time": 1575759600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0092,
                "precipProbability": 0.22,
                "precipType": "rain",
                "temperature": 60.35,
                "apparentTemperature": 60.37,
                "dewPoint": 57.75,
                "humidity": 0.91,
                "pressure": 1019.7,
                "windSpeed": 4.42,
                "windGust": 7.15,
                "windBearing": 163,
                "cloudCover": 0.99,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 292.2
            }, {
                "time": 1575763200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0114,
                "precipProbability": 0.27,
                "precipType": "rain",
                "temperature": 59.02,
                "apparentTemperature": 59.16,
                "dewPoint": 58.01,
                "humidity": 0.96,
                "pressure": 1019.6,
                "windSpeed": 4.43,
                "windGust": 7.43,
                "windBearing": 170,
                "cloudCover": 0.99,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 292.9
            }, {
                "time": 1575766800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.012,
                "precipProbability": 0.29,
                "precipType": "rain",
                "temperature": 57.28,
                "apparentTemperature": 57.6,
                "dewPoint": 57.28,
                "humidity": 1,
                "pressure": 1019.5,
                "windSpeed": 4.4,
                "windGust": 7.25,
                "windBearing": 176,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 292.9
            }, {
                "time": 1575770400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0117,
                "precipProbability": 0.29,
                "precipType": "rain",
                "temperature": 56.2,
                "apparentTemperature": 56.47,
                "dewPoint": 56.2,
                "humidity": 1,
                "pressure": 1019.5,
                "windSpeed": 4.3,
                "windGust": 6.8,
                "windBearing": 180,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 7.137,
                "ozone": 292.6
            }, {
                "time": 1575774000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0114,
                "precipProbability": 0.31,
                "precipType": "rain",
                "temperature": 55.56,
                "apparentTemperature": 55.77,
                "dewPoint": 55.56,
                "humidity": 1,
                "pressure": 1019.5,
                "windSpeed": 4.21,
                "windGust": 6.45,
                "windBearing": 181,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 4.993,
                "ozone": 292.6
            }, {
                "time": 1575777600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0113,
                "precipProbability": 0.33,
                "precipType": "rain",
                "temperature": 55.28,
                "apparentTemperature": 55.36,
                "dewPoint": 55.28,
                "humidity": 1,
                "pressure": 1019.6,
                "windSpeed": 4.2,
                "windGust": 6.41,
                "windBearing": 181,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 5.653,
                "ozone": 293.3
            }, {
                "time": 1575781200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0124,
                "precipProbability": 0.35,
                "precipType": "rain",
                "temperature": 55.25,
                "apparentTemperature": 55.25,
                "dewPoint": 55.17,
                "humidity": 1,
                "pressure": 1019.7,
                "windSpeed": 4.24,
                "windGust": 6.48,
                "windBearing": 180,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 7.651,
                "ozone": 294.4
            }, {
                "time": 1575784800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0144,
                "precipProbability": 0.35,
                "precipType": "rain",
                "temperature": 55.48,
                "apparentTemperature": 55.48,
                "dewPoint": 54.41,
                "humidity": 0.96,
                "pressure": 1019.8,
                "windSpeed": 4.21,
                "windGust": 6.36,
                "windBearing": 181,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 8.877,
                "ozone": 295.4
            }, {
                "time": 1575788400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0169,
                "precipProbability": 0.36,
                "precipType": "rain",
                "temperature": 55.48,
                "apparentTemperature": 55.48,
                "dewPoint": 53.8,
                "humidity": 0.94,
                "pressure": 1019.6,
                "windSpeed": 4.04,
                "windGust": 5.81,
                "windBearing": 185,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 8.276,
                "ozone": 296.6
            }, {
                "time": 1575792000,
                "summary": "Possible Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0197,
                "precipProbability": 0.4,
                "precipType": "rain",
                "temperature": 55.41,
                "apparentTemperature": 55.41,
                "dewPoint": 53.21,
                "humidity": 0.92,
                "pressure": 1019.3,
                "windSpeed": 3.82,
                "windGust": 5.15,
                "windBearing": 190,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 6.847,
                "ozone": 297.8
            }, {
                "time": 1575795600,
                "summary": "Possible Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0203,
                "precipProbability": 0.42,
                "precipType": "rain",
                "temperature": 55.43,
                "apparentTemperature": 55.43,
                "dewPoint": 53.07,
                "humidity": 0.92,
                "pressure": 1019,
                "windSpeed": 3.68,
                "windGust": 4.89,
                "windBearing": 192,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 5.81,
                "ozone": 298.8
            }, {
                "time": 1575799200,
                "summary": "Possible Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0169,
                "precipProbability": 0.41,
                "precipType": "rain",
                "temperature": 55.47,
                "apparentTemperature": 55.47,
                "dewPoint": 53.03,
                "humidity": 0.92,
                "pressure": 1018.6,
                "windSpeed": 3.67,
                "windGust": 4.74,
                "windBearing": 186,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 5.387,
                "ozone": 299.3
            }, {
                "time": 1575802800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0128,
                "precipProbability": 0.36,
                "precipType": "rain",
                "temperature": 55.6,
                "apparentTemperature": 55.6,
                "dewPoint": 53.08,
                "humidity": 0.91,
                "pressure": 1018.3,
                "windSpeed": 3.75,
                "windGust": 4.8,
                "windBearing": 245,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 5.337,
                "ozone": 299.6
            }, {
                "time": 1575806400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0101,
                "precipProbability": 0.34,
                "precipType": "rain",
                "temperature": 55.56,
                "apparentTemperature": 55.56,
                "dewPoint": 53.1,
                "humidity": 0.91,
                "pressure": 1018.1,
                "windSpeed": 3.84,
                "windGust": 5.03,
                "windBearing": 231,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 6.009,
                "ozone": 300.1
            }, {
                "time": 1575810000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0075,
                "precipProbability": 0.3,
                "precipType": "rain",
                "temperature": 55.44,
                "apparentTemperature": 55.44,
                "dewPoint": 53.64,
                "humidity": 0.94,
                "pressure": 1018.2,
                "windSpeed": 3.9,
                "windGust": 4.97,
                "windBearing": 212,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 8.234,
                "ozone": 301.2
            }, {
                "time": 1575813600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0055,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 55.21,
                "apparentTemperature": 55.21,
                "dewPoint": 53.84,
                "humidity": 0.95,
                "pressure": 1018.4,
                "windSpeed": 3.97,
                "windGust": 4.83,
                "windBearing": 251,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.3
            }, {
                "time": 1575817200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0048,
                "precipProbability": 0.21,
                "precipType": "rain",
                "temperature": 55.41,
                "apparentTemperature": 55.41,
                "dewPoint": 54.14,
                "humidity": 0.95,
                "pressure": 1018.6,
                "windSpeed": 4.15,
                "windGust": 4.94,
                "windBearing": 244,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.4
            }, {
                "time": 1575820800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.005,
                "precipProbability": 0.22,
                "precipType": "rain",
                "temperature": 55.9,
                "apparentTemperature": 55.9,
                "dewPoint": 54.7,
                "humidity": 0.96,
                "pressure": 1018.9,
                "windSpeed": 4.42,
                "windGust": 5.33,
                "windBearing": 249,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.9
            }, {
                "time": 1575824400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0065,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 57.4,
                "apparentTemperature": 57.4,
                "dewPoint": 55.19,
                "humidity": 0.92,
                "pressure": 1019.1,
                "windSpeed": 4.82,
                "windGust": 5.98,
                "windBearing": 209,
                "cloudCover": 1,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 304.2
            }, {
                "time": 1575828000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0077,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 57.46,
                "apparentTemperature": 57.46,
                "dewPoint": 54.88,
                "humidity": 0.91,
                "pressure": 1019.1,
                "windSpeed": 5.39,
                "windGust": 6.79,
                "windBearing": 234,
                "cloudCover": 0.98,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 304.5
            }, {
                "time": 1575831600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0062,
                "precipProbability": 0.16,
                "precipType": "rain",
                "temperature": 59.15,
                "apparentTemperature": 59.15,
                "dewPoint": 54.59,
                "humidity": 0.85,
                "pressure": 1018.7,
                "windSpeed": 6.26,
                "windGust": 7.91,
                "windBearing": 245,
                "cloudCover": 0.9,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 304.7
            }, {
                "time": 1575835200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0041,
                "precipProbability": 0.09,
                "precipType": "rain",
                "temperature": 60.69,
                "apparentTemperature": 60.69,
                "dewPoint": 54.74,
                "humidity": 0.81,
                "pressure": 1018,
                "windSpeed": 7.27,
                "windGust": 9.18,
                "windBearing": 233,
                "cloudCover": 0.78,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 304.9
            }, {
                "time": 1575838800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0032,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 61.55,
                "apparentTemperature": 61.55,
                "dewPoint": 54.71,
                "humidity": 0.78,
                "pressure": 1017.5,
                "windSpeed": 7.97,
                "windGust": 10.13,
                "windBearing": 238,
                "cloudCover": 0.69,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 305.4
            }, {
                "time": 1575842400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0026,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 60.75,
                "apparentTemperature": 60.75,
                "dewPoint": 54.52,
                "humidity": 0.8,
                "pressure": 1017,
                "windSpeed": 8.28,
                "windGust": 10.59,
                "windBearing": 245,
                "cloudCover": 0.65,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 306.3
            }, {
                "time": 1575846000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0022,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperature": 60.55,
                "apparentTemperature": 60.55,
                "dewPoint": 54.12,
                "humidity": 0.79,
                "pressure": 1016.7,
                "windSpeed": 8.31,
                "windGust": 10.72,
                "windBearing": 247,
                "cloudCover": 0.62,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 307.5
            }, {
                "time": 1575849600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0023,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 57.55,
                "apparentTemperature": 57.55,
                "dewPoint": 53.48,
                "humidity": 0.86,
                "pressure": 1016.6,
                "windSpeed": 8.1,
                "windGust": 10.53,
                "windBearing": 242,
                "cloudCover": 0.59,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 309.3
            }, {
                "time": 1575853200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0027,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperature": 55.57,
                "apparentTemperature": 55.57,
                "dewPoint": 53.36,
                "humidity": 0.92,
                "pressure": 1016.7,
                "windSpeed": 7.56,
                "windGust": 9.94,
                "windBearing": 195,
                "cloudCover": 0.6,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 311.8
            }, {
                "time": 1575856800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0038,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 53.64,
                "apparentTemperature": 53.64,
                "dewPoint": 52.07,
                "humidity": 0.94,
                "pressure": 1017.1,
                "windSpeed": 6.78,
                "windGust": 9.01,
                "windBearing": 336,
                "cloudCover": 0.63,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 314.8
            }
        ]
    },
    "daily": {
        "summary": "Light rain today through Sunday.",
        "icon": "rain",
        "data": [{
                "time": 1575619200,
                "summary": "Light rain in the afternoon.",
                "icon": "rain",
                "sunriseTime": 1575643620,
                "sunsetTime": 1575679500,
                "moonPhase": 0.34,
                "precipIntensity": 0.0034,
                "precipIntensityMax": 0.0347,
                "precipIntensityMaxTime": 1575671640,
                "precipProbability": 0.91,
                "precipType": "rain",
                "temperatureHigh": 65.94,
                "temperatureHighTime": 1575662280,
                "temperatureLow": 54.3,
                "temperatureLowTime": 1575725640,
                "apparentTemperatureHigh": 65.44,
                "apparentTemperatureHighTime": 1575662280,
                "apparentTemperatureLow": 54.79,
                "apparentTemperatureLowTime": 1575725640,
                "dewPoint": 49.46,
                "humidity": 0.76,
                "pressure": 1020.4,
                "windSpeed": 4.16,
                "windGust": 13.66,
                "windGustTime": 1575641940,
                "windBearing": 65,
                "cloudCover": 0.57,
                "uvIndex": 3,
                "uvIndexTime": 1575661200,
                "visibility": 10,
                "ozone": 287.9,
                "temperatureMin": 52.41,
                "temperatureMinTime": 1575644100,
                "temperatureMax": 65.94,
                "temperatureMaxTime": 1575662280,
                "apparentTemperatureMin": 52.9,
                "apparentTemperatureMinTime": 1575644100,
                "apparentTemperatureMax": 65.44,
                "apparentTemperatureMaxTime": 1575662280
            }, {
                "time": 1575705600,
                "summary": "Possible light rain until morning, starting again in the evening.",
                "icon": "rain",
                "sunriseTime": 1575730080,
                "sunsetTime": 1575765960,
                "moonPhase": 0.37,
                "precipIntensity": 0.0112,
                "precipIntensityMax": 0.0284,
                "precipIntensityMaxTime": 1575725760,
                "precipProbability": 0.86,
                "precipType": "rain",
                "temperatureHigh": 61.86,
                "temperatureHighTime": 1575755760,
                "temperatureLow": 54.72,
                "temperatureLowTime": 1575813660,
                "apparentTemperatureHigh": 61.36,
                "apparentTemperatureHighTime": 1575755760,
                "apparentTemperatureLow": 55.21,
                "apparentTemperatureLowTime": 1575813660,
                "dewPoint": 54.45,
                "humidity": 0.91,
                "pressure": 1020.5,
                "windSpeed": 4.29,
                "windGust": 8.14,
                "windGustTime": 1575733860,
                "windBearing": 137,
                "cloudCover": 0.96,
                "uvIndex": 2,
                "uvIndexTime": 1575747960,
                "visibility": 9.19,
                "ozone": 290.5,
                "temperatureMin": 54.3,
                "temperatureMinTime": 1575725640,
                "temperatureMax": 61.86,
                "temperatureMaxTime": 1575755760,
                "apparentTemperatureMin": 54.79,
                "apparentTemperatureMinTime": 1575725640,
                "apparentTemperatureMax": 61.36,
                "apparentTemperatureMaxTime": 1575755760
            }, {
                "time": 1575792000,
                "summary": "Possible drizzle in the morning.",
                "icon": "rain",
                "sunriseTime": 1575816540,
                "sunsetTime": 1575852360,
                "moonPhase": 0.4,
                "precipIntensity": 0.0066,
                "precipIntensityMax": 0.0204,
                "precipIntensityMaxTime": 1575794640,
                "precipProbability": 0.79,
                "precipType": "rain",
                "temperatureHigh": 62.05,
                "temperatureHighTime": 1575838800,
                "temperatureLow": 48.67,
                "temperatureLowTime": 1575899880,
                "apparentTemperatureHigh": 61.55,
                "apparentTemperatureHighTime": 1575838800,
                "apparentTemperatureLow": 46.92,
                "apparentTemperatureLowTime": 1575901320,
                "dewPoint": 52.71,
                "humidity": 0.89,
                "pressure": 1018,
                "windSpeed": 5.27,
                "windGust": 10.73,
                "windGustTime": 1575845700,
                "windBearing": 241,
                "cloudCover": 0.77,
                "uvIndex": 2,
                "uvIndexTime": 1575834960,
                "visibility": 9.147,
                "ozone": 309.2,
                "temperatureMin": 50.56,
                "temperatureMinTime": 1575878400,
                "temperatureMax": 62.05,
                "temperatureMaxTime": 1575838800,
                "apparentTemperatureMin": 51.05,
                "apparentTemperatureMinTime": 1575878400,
                "apparentTemperatureMax": 61.55,
                "apparentTemperatureMaxTime": 1575838800
            }, {
                "time": 1575878400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1575902940,
                "sunsetTime": 1575938760,
                "moonPhase": 0.43,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.0027,
                "precipIntensityMaxTime": 1575878400,
                "precipProbability": 0.17,
                "precipType": "rain",
                "temperatureHigh": 65.29,
                "temperatureHighTime": 1575928080,
                "temperatureLow": 46.88,
                "temperatureLowTime": 1575987360,
                "apparentTemperatureHigh": 64.79,
                "apparentTemperatureHighTime": 1575928080,
                "apparentTemperatureLow": 45.95,
                "apparentTemperatureLowTime": 1575987360,
                "dewPoint": 41.91,
                "humidity": 0.63,
                "pressure": 1019.8,
                "windSpeed": 5.41,
                "windGust": 8.92,
                "windGustTime": 1575933660,
                "windBearing": 5,
                "cloudCover": 0.08,
                "uvIndex": 3,
                "uvIndexTime": 1575921000,
                "visibility": 10,
                "ozone": 314.6,
                "temperatureMin": 48.67,
                "temperatureMinTime": 1575899880,
                "temperatureMax": 65.29,
                "temperatureMaxTime": 1575928080,
                "apparentTemperatureMin": 46.92,
                "apparentTemperatureMinTime": 1575901320,
                "apparentTemperatureMax": 64.79,
                "apparentTemperatureMaxTime": 1575928080
            }, {
                "time": 1575964800,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1575989400,
                "sunsetTime": 1576025160,
                "moonPhase": 0.47,
                "precipIntensity": 0,
                "precipIntensityMax": 0.0002,
                "precipIntensityMaxTime": 1575999600,
                "precipProbability": 0.02,
                "temperatureHigh": 65.62,
                "temperatureHighTime": 1576014780,
                "temperatureLow": 48.75,
                "temperatureLowTime": 1576075560,
                "apparentTemperatureHigh": 65.12,
                "apparentTemperatureHighTime": 1576014780,
                "apparentTemperatureLow": 48.2,
                "apparentTemperatureLowTime": 1576075320,
                "dewPoint": 36.66,
                "humidity": 0.51,
                "pressure": 1023.1,
                "windSpeed": 3.72,
                "windGust": 6.13,
                "windGustTime": 1575968640,
                "windBearing": 13,
                "cloudCover": 0.65,
                "uvIndex": 2,
                "uvIndexTime": 1576006320,
                "visibility": 10,
                "ozone": 299.1,
                "temperatureMin": 46.88,
                "temperatureMinTime": 1575987360,
                "temperatureMax": 65.62,
                "temperatureMaxTime": 1576014780,
                "apparentTemperatureMin": 45.95,
                "apparentTemperatureMinTime": 1575987360,
                "apparentTemperatureMax": 65.12,
                "apparentTemperatureMaxTime": 1576014780
            }, {
                "time": 1576051200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1576075860,
                "sunsetTime": 1576111560,
                "moonPhase": 0.5,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1576123500,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperatureHigh": 65.44,
                "temperatureHighTime": 1576100940,
                "temperatureLow": 49.94,
                "temperatureLowTime": 1576158960,
                "apparentTemperatureHigh": 64.94,
                "apparentTemperatureHighTime": 1576100940,
                "apparentTemperatureLow": 50.43,
                "apparentTemperatureLowTime": 1576158960,
                "dewPoint": 34.19,
                "humidity": 0.45,
                "pressure": 1022.1,
                "windSpeed": 3.96,
                "windGust": 6.3,
                "windGustTime": 1576110900,
                "windBearing": 352,
                "cloudCover": 0.34,
                "uvIndex": 3,
                "uvIndexTime": 1576094220,
                "visibility": 10,
                "ozone": 306,
                "temperatureMin": 48.75,
                "temperatureMinTime": 1576075560,
                "temperatureMax": 65.44,
                "temperatureMaxTime": 1576100940,
                "apparentTemperatureMin": 48.2,
                "apparentTemperatureMinTime": 1576075320,
                "apparentTemperatureMax": 64.94,
                "apparentTemperatureMaxTime": 1576100940
            }, {
                "time": 1576137600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1576162260,
                "sunsetTime": 1576197960,
                "moonPhase": 0.53,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1576150560,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperatureHigh": 70.3,
                "temperatureHighTime": 1576186740,
                "temperatureLow": 52.6,
                "temperatureLowTime": 1576245480,
                "apparentTemperatureHigh": 69.8,
                "apparentTemperatureHighTime": 1576186740,
                "apparentTemperatureLow": 53.09,
                "apparentTemperatureLowTime": 1576245480,
                "dewPoint": 26.41,
                "humidity": 0.3,
                "pressure": 1021.6,
                "windSpeed": 4.81,
                "windGust": 6.96,
                "windGustTime": 1576194960,
                "windBearing": 0,
                "cloudCover": 0.22,
                "uvIndex": 3,
                "uvIndexTime": 1576180440,
                "visibility": 10,
                "ozone": 279.5,
                "temperatureMin": 49.94,
                "temperatureMinTime": 1576158960,
                "temperatureMax": 70.3,
                "temperatureMaxTime": 1576186740,
                "apparentTemperatureMin": 50.43,
                "apparentTemperatureMinTime": 1576158960,
                "apparentTemperatureMax": 69.8,
                "apparentTemperatureMaxTime": 1576186740
            }, {
                "time": 1576224000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1576248720,
                "sunsetTime": 1576284360,
                "moonPhase": 0.57,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1576278000,
                "precipProbability": 0,
                "temperatureHigh": 73.7,
                "temperatureHighTime": 1576272780,
                "temperatureLow": 52.57,
                "temperatureLowTime": 1576331940,
                "apparentTemperatureHigh": 73.2,
                "apparentTemperatureHighTime": 1576272780,
                "apparentTemperatureLow": 53.06,
                "apparentTemperatureLowTime": 1576331940,
                "dewPoint": 26.38,
                "humidity": 0.27,
                "pressure": 1020.7,
                "windSpeed": 3.5,
                "windGust": 5.14,
                "windGustTime": 1576229760,
                "windBearing": 1,
                "cloudCover": 0.14,
                "uvIndex": 3,
                "uvIndexTime": 1576266540,
                "visibility": 10,
                "ozone": 269.9,
                "temperatureMin": 52.6,
                "temperatureMinTime": 1576245480,
                "temperatureMax": 73.7,
                "temperatureMaxTime": 1576272780,
                "apparentTemperatureMin": 53.09,
                "apparentTemperatureMinTime": 1576245480,
                "apparentTemperatureMax": 73.2,
                "apparentTemperatureMaxTime": 1576272780
            }
        ]
    },
    "flags": {
        "sources": ["nwspa", "cmc", "gfs", "hrrr", "icon", "isd", "madis", "nam", "sref", "darksky", "nearest-precip"],
        "nearest-station": 0.825,
        "units": "us"
    },
    "offset": -8
})
	
})

app.listen(1234, () => {
  console.log("Server is listening on port: 1234");
});